// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

#nullable disable

namespace Persistencia.Data.Migrations
{
    [DbContext(typeof(CodeContext))]
    [Migration("20240305223413_CreateMig")]
    partial class CreateMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dominio.Entidades.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("Ano");

                    b.Property<string>("Director")
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("Director");

                    b.Property<string>("Genero")
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("Genero");

                    b.Property<string>("Titulo")
                        .HasMaxLength(80)
                        .HasColumnType("varchar")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Pelicula", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
